In [2]:
data_dir = "data/"
lc_fname = "listed_company"
#pr_fname = "test.csv"
#pr_fname = "pressrelease_all.csv"
matching_fname = "matchings"
kabuka_fname = "kabuka_tse1"
market_fname = "market_tse1"

In [3]:
lc_code = {}
with open(data_dir + lc_fname, 'r') as f:
    for line in f:
        data = line.strip().split('\t')
        lc_code[data[0]] = data[2]
        
#print(lc_code)

In [4]:
matching = {}
with open(matching_fname, 'r') as f:
    for line in f:
        data = line.strip().split('\t')
        comp = data[2].strip().split(' ')
        comp_code = [lc_code[x] for x in comp]
        matching[data[0]] = (data[1], comp_code, comp)
        
#print(matching)
# {articleid : (date, [code], [name])}

In [98]:
# TOPIXデータの読み込み

topix = []
with open(data_dir + market_fname, 'r') as f:
    for line in f:
        data = line.strip().split(',')
        #comp_code = data[0]
        for x in data[1:]:
            date, value = x.split(':')
            topix.append((date, value))
            
import pandas as pd
dates = [x[0] for x in topix]
values = [float(x[1]) for x in topix]

market = pd.DataFrame({"value": values})
market.index = pd.to_datetime(dates)

In [99]:
market

              value
2000-01-04  1717.47
2000-01-05  1651.84
2000-01-06  1609.59
2000-01-07  1599.01
2000-01-11  1678.82
2000-01-12  1656.92
2000-01-13  1657.97
2000-01-14  1648.24
2000-01-17  1681.97
2000-01-18  1665.84
2000-01-19  1631.28
2000-01-20  1633.11
2000-01-21  1627.14
2000-01-24  1647.96
2000-01-25  1632.57
2000-01-26  1664.09
2000-01-27  1685.90
2000-01-28  1702.61
2000-01-31  1707.96
2000-02-01  1697.15
2000-02-02  1711.86
2000-02-03  1729.48
2000-02-04  1741.22
2000-02-07  1754.78
2000-02-08  1737.55
2000-02-09  1747.83
2000-02-10  1729.47
2000-02-14  1717.41
2000-02-15  1690.14
2000-02-16  1691.12
...             ...
2010-11-17   850.30
2010-11-18   868.81
2010-11-19   869.52
2010-11-22   875.48
2010-11-24   866.57
2010-11-25   869.81
2010-11-26   866.81
2010-11-29   874.59
2010-11-30   860.94
2010-12-01   866.07
2010-12-02   877.21
2010-12-03   879.22
2010-12-06   881.41
2010-12-07   879.10
2010-12-08   887.39
2010-12-09   891.60
2010-12-10   888.22
2010-12-13   897.40
2010-12-14   901.89
2010-12-15   902.42
2010-12-16   903.84
2010-12-17   903.14
2010-12-20   898.55
2010-12-21   906.21
2010-12-22   905.78
2010-12-24   901.66
2010-12-27   904.68
2010-12-28   902.83
2010-12-29   908.01
2010-12-30   898.80

[2702 rows x 1 columns]

In [29]:
# 株価データの読み込み、欠損値がある企業はどうする？

from collections import defaultdict

kabuka = defaultdict(list)
with open(data_dir + kabuka_fname, 'r') as f:
    for line in f:
        data = line.strip().split(',')
        comp_code = data[0]
        for x in data[1:]:
            date, value = x.split(':')
            kabuka[comp_code].append((date, value))

In [30]:
kabuka['1301']

[('20000104', '133'),
 ('20000105', '135'),
 ('20000106', '135'),
 ('20000107', '137'),
 ('20000111', '135'),
 ('20000112', '137'),
 ('20000113', '139'),
 ('20000114', '141'),
 ('20000117', '160'),
 ('20000118', '152'),
 ('20000119', '152'),
 ('20000120', '163'),
 ('20000121', '153'),
 ('20000124', '147'),
 ('20000125', '144'),
 ('20000126', '143'),
 ('20000127', '143'),
 ('20000128', '140'),
 ('20000131', '144'),
 ('20000201', '141'),
 ('20000202', '140'),
 ('20000203', '140'),
 ('20000204', '138'),
 ('20000207', '141'),
 ('20000208', '147'),
 ('20000209', '144'),
 ('20000210', '142'),
 ('20000214', '144'),
 ('20000215', '147'),
 ('20000216', '153'),
 ('20000217', '143'),
 ('20000218', '141'),
 ('20000221', '141'),
 ('20000222', '139'),
 ('20000223', '138'),
 ('20000224', '134'),
 ('20000225', '137'),
 ('20000228', '132'),
 ('20000229', '135'),
 ('20000301', '133'),
 ('20000302', '133'),
 ('20000303', '136'),
 ('20000306', '147'),
 ('20000307', '150'),
 ('20000308', '145'),
 ('20000309', '145'),
 ('20000310', '147'),
 ('20000313', '158'),
 ('20000314', '153'),
 ('20000315', '151'),
 ('20000316', '147'),
 ('20000317', '151'),
 ('20000321', '146'),
 ('20000322', '154'),
 ('20000323', '147'),
 ('20000324', '154'),
 ('20000327', '152'),
 ('20000328', '153'),
 ('20000329', '148'),
 ('20000330', '143'),
 ('20000331', '145'),
 ('20000403', '150'),
 ('20000404', '150'),
 ('20000405', '152'),
 ('20000406', '155'),
 ('20000407', '153'),
 ('20000410', '153'),
 ('20000411', '152'),
 ('20000412', '155'),
 ('20000413', '158'),
 ('20000414', '158'),
 ('20000417', '152'),
 ('20000418', '144'),
 ('20000419', '149'),
 ('20000420', '138'),
 ('20000421', '123'),
 ('20000424', '140'),
 ('20000425', '137'),
 ('20000426', '134'),
 ('20000427', '135'),
 ('20000428', '130'),
 ('20000501', '133'),
 ('20000502', '135'),
 ('20000508', '138'),
 ('20000509', '144'),
 ('20000510', '147'),
 ('20000511', '145'),
 ('20000512', '142'),
 ('20000515', '145'),
 ('20000516', '143'),
 ('20000517', '142'),
 ('20000518', '147'),
 ('20000519', '142'),
 ('20000522', '147'),
 ('20000523', '147'),
 ('20000524', '144'),
 ('20000525', '146'),
 ('20000526', '142'),
 ('20000529', '146'),
 ('20000530', '142'),
 ('20000531', '140'),
 ('20000601', '145'),
 ('20000602', '143'),
 ('20000605', '142'),
 ('20000606', '141'),
 ('20000607', '144'),
 ('20000608', '145'),
 ('20000609', '144'),
 ('20000612', '150'),
 ('20000613', '154'),
 ('20000614', '154'),
 ('20000615', '151'),
 ('20000616', '156'),
 ('20000619', '153'),
 ('20000620', '154'),
 ('20000621', '154'),
 ('20000622', '149'),
 ('20000623', '152'),
 ('20000626', '155'),
 ('20000627', '163'),
 ('20000628', '164'),
 ('20000629', '161'),
 ('20000630', '163'),
 ('20000703', '167'),
 ('20000704', '165'),
 ('20000705', '161'),
 ('20000706', '160'),
 ('20000707', '160'),
 ('20000710', '157'),
 ('20000711', '157'),
 ('20000712', '158'),
 ('20000713', '153'),
 ('20000714', '157'),
 ('20000717', '157'),
 ('20000718', '152'),
 ('20000719', '148'),
 ('20000721', '151'),
 ('20000724', '145'),
 ('20000725', '151'),
 ('20000726', '146'),
 ('20000727', '148'),
 ('20000728', '146'),
 ('20000731', '142'),
 ('20000801', '142'),
 ('20000802', '145'),
 ('20000803', '142'),
 ('20000804', '144'),
 ('20000807', '144'),
 ('20000808', '142'),
 ('20000809', '145'),
 ('20000810', '146'),
 ('20000811', '144'),
 ('20000814', '143'),
 ('20000815', '144'),
 ('20000816', '144'),
 ('20000817', '143'),
 ('20000818', '145'),
 ('20000821', '143'),
 ('20000822', '151'),
 ('20000823', '142'),
 ('20000824', '147'),
 ('20000825', '146'),
 ('20000828', '146'),
 ('20000829', '144'),
 ('20000830', '142'),
 ('20000831', '145'),
 ('20000901', '142'),
 ('20000904', '141'),
 ('20000905', '142'),
 ('20000906', '144'),
 ('20000907', '143'),
 ('20000908', '142'),
 ('20000911', '142'),
 ('20000912', '143'),
 ('20000913', '144'),
 ('20000914', '143'),
 ('20000918', '139'),
 ('20000919', '140'),
 ('20000920', '141'),
 ('20000921', '139'),
 ('20000922', '142'),
 ('20000925', '142'),
 ('20000926', '142'),
 ('20000927', '142'),
 ('20000928', '141'),
 ('20000929', '138'),
 ('20001002', '139'),
 ('20001003', '138'),
 ('20001004', '141'),
 ('20001005', '141'),
 ('20001006', '140'),
 ('20001010', '135'),
 ('20001011', '137'),
 ('20001012', '138'),
 ('20001013', '135'),
 ('20001016', '136'),
 ('20001017', '136'),
 ('20001018', '136'),
 ('20001019', '134'),
 ('20001020', '133'),
 ('20001023', '132'),
 ('20001024', '134'),
 ('20001025', '136'),
 ('20001026', '142'),
 ('20001027', '132'),
 ('20001030', '138'),
 ('20001031', '138'),
 ('20001101', '139'),
 ('20001102', '138'),
 ('20001106', '143'),
 ('20001107', '145'),
 ('20001108', '145'),
 ('20001109', '139'),
 ('20001110', '143'),
 ('20001113', '138'),
 ('20001114', '143'),
 ('20001115', '143'),
 ('20001116', '141'),
 ('20001117', '141'),
 ('20001120', '142'),
 ('20001121', '140'),
 ('20001122', '140'),
 ('20001124', '140'),
 ('20001127', '143'),
 ('20001128', '141'),
 ('20001129', '141'),
 ('20001130', '146'),
 ('20001201', '147'),
 ('20001204', '146'),
 ('20001205', '143'),
 ('20001206', '143'),
 ('20001207', '142'),
 ('20001208', '142'),
 ('20001211', '143'),
 ('20001212', '145'),
 ('20001213', '145'),
 ('20001214', '145'),
 ('20001215', '143'),
 ('20001218', '142'),
 ('20001219', '142'),
 ('20001220', '141'),
 ('20001221', '142'),
 ('20001222', '140'),
 ('20001225', '143'),
 ('20001226', '142'),
 ('20001227', '142'),
 ('20001228', '142'),
 ('20001229', '140'),
 ('20010104', '139'),
 ('20010105', '133'),
 ('20010109', '131'),
 ('20010110', '131'),
 ('20010111', '131'),
 ('20010112', '131'),
 ('20010115', '132'),
 ('20010116', '133'),
 ('20010117', '132'),
 ('20010118', '132'),
 ('20010119', '132'),
 ('20010122', '135'),
 ('20010123', '135'),
 ('20010124', '133'),
 ('20010125', '133'),
 ('20010126', '133'),
 ('20010129', '142'),
 ('20010130', '141'),
 ('20010131', '141'),
 ('20010201', '138'),
 ('20010202', '141'),
 ('20010205', '140'),
 ('20010206', '140'),
 ('20010207', '144'),
 ('20010208', '144'),
 ('20010209', '148'),
 ('20010213', '146'),
 ('20010214', '149'),
 ('20010215', '152'),
 ('20010216', '149'),
 ('20010219', '148'),
 ('20010220', '150'),
 ('20010221', '148'),
 ('20010222', '146'),
 ('20010223', '146'),
 ('20010226', '148'),
 ('20010227', '151'),
 ('20010228', '154'),
 ('20010301', '154'),
 ('20010302', '146'),
 ('20010305', '143'),
 ('20010306', '145'),
 ('20010307', '149'),
 ('20010308', '146'),
 ('20010309', '147'),
 ('20010312', '143'),
 ('20010313', '140'),
 ('20010314', '145'),
 ('20010315', '142'),
 ('20010316', '141'),
 ('20010319', '143'),
 ('20010321', '153'),
 ('20010322', '149'),
 ('20010323', '150'),
 ('20010326', '157'),
 ('20010327', '152'),
 ('20010328', '152'),
 ('20010329', '152'),
 ('20010330', '148'),
 ('20010402', '148'),
 ('20010403', '151'),
 ('20010404', '153'),
 ('20010405', '152'),
 ('20010406', '152'),
 ('20010409', '147'),
 ('20010410', '147'),
 ('20010411', '155'),
 ('20010412', '151'),
 ('20010413', '163'),
 ('20010416', '161'),
 ('20010417', '165'),
 ('20010418', '172'),
 ('20010419', '169'),
 ('20010420', '164'),
 ('20010423', '165'),
 ('20010424', '170'),
 ('20010425', '169'),
 ('20010426', '170'),
 ('20010427', '166'),
 ('20010501', '173'),
 ('20010502', '168'),
 ('20010507', '163'),
 ('20010508', '158'),
 ('20010509', '153'),
 ('20010510', '155'),
 ('20010511', '157'),
 ('20010514', '154'),
 ('20010515', '156'),
 ('20010516', '152'),
 ('20010517', '151'),
 ('20010518', '152'),
 ('20010521', '154'),
 ('20010522', '151'),
 ('20010523', '152'),
 ('20010524', '153'),
 ('20010525', '153'),
 ('20010528', '150'),
 ('20010529', '150'),
 ('20010530', '147'),
 ('20010531', '146'),
 ('20010601', '145'),
 ('20010604', '145'),
 ('20010605', '146'),
 ('20010606', '145'),
 ('20010607', '142'),
 ('20010608', '147'),
 ('20010611', '147'),
 ('20010612', '147'),
 ('20010613', '148'),
 ('20010614', '152'),
 ('20010615', '152'),
 ('20010618', '153'),
 ('20010619', '153'),
 ('20010620', '156'),
 ('20010621', '155'),
 ('20010622', '154'),
 ('20010625', '153'),
 ('20010626', '161'),
 ('20010627', '165'),
 ('20010628', '158'),
 ('20010629', '162'),
 ('20010702', '158'),
 ('20010703', '158'),
 ('20010704', '153'),
 ('20010705', '156'),
 ('20010706', '152'),
 ('20010709', '153'),
 ('20010710', '150'),
 ('20010711', '149'),
 ('20010712', '153'),
 ('20010713', '151'),
 ('20010716', '151'),
 ('20010717', '150'),
 ('20010718', '150'),
 ('20010719', '148'),
 ('20010723', '145'),
 ('20010724', '144'),
 ('20010725', '142'),
 ('20010726', '145'),
 ('20010727', '148'),
 ('20010730', '145'),
 ('20010731', '145'),
 ('20010801', '143'),
 ('20010802', '146'),
 ('20010803', '145'),
 ('20010806', '149'),
 ('20010807', '149'),
 ('20010808', '147'),
 ('20010809', '146'),
 ('20010810', '148'),
 ('20010813', '144'),
 ('20010814', '152'),
 ('20010815', '147'),
 ('20010816', '145'),
 ('20010817', '144'),
 ('20010820', '141'),
 ('20010821', '142'),
 ('20010822', '142'),
 ('20010823', '142'),
 ('20010824', '142'),
 ('20010827', '143'),
 ('20010828', '143'),
 ('20010829', '142'),
 ('20010830', '143'),
 ('20010831', '138'),
 ('20010903', '138'),
 ('20010904', '141'),
 ('20010905', '135'),
 ('20010906', '136'),
 ('20010907', '134'),
 ('20010910', '126'),
 ('20010911', '130'),
 ('20010912', '128'),
 ('20010913', '133'),
 ('20010914', '145'),
 ('20010917', '137'),
 ('20010918', '142'),
 ('20010919', '137'),
 ('20010920', '135'),
 ('20010921', '130'),
 ('20010925', '134'),
 ('20010926', '134'),
 ('20010927', '138'),
 ('20010928', '138'),
 ('20011001', '140'),
 ('20011002', '139'),
 ('20011003', '138'),
 ('20011004', '145'),
 ('20011005', '144'),
 ('20011009', '141'),
 ('20011010', '140'),
 ('20011011', '142'),
 ('20011012', '148'),
 ('20011015', '146'),
 ('20011016', '148'),
 ('20011017', '142'),
 ('20011018', '140'),
 ('20011019', '139'),
 ('20011022', '137'),
 ('20011023', '142'),
 ('20011024', '141'),
 ('20011025', '143'),
 ('20011026', '140'),
 ('20011029', '141'),
 ('20011030', '141'),
 ('20011031', '141'),
 ('20011101', '137'),
 ('20011102', '136'),
 ('20011105', '138'),
 ('20011106', '141'),
 ('20011107', '139'),
 ('20011108', '141'),
 ('20011109', '135'),
 ('20011112', '135'),
 ('20011113', '134'),
 ('20011114', '134'),
 ('20011115', '137'),
 ('20011116', '138'),
 ('20011119', '139'),
 ('20011120', '138'),
 ('20011121', '141'),
 ('20011122', '140'),
 ('20011126', '142'),
 ('20011127', '141'),
 ('20011128', '138'),
 ('20011129', '141'),
 ('20011130', '141'),
 ('20011203', '137'),
 ('20011204', '138'),
 ('20011205', '136'),
 ('20011206', '136'),
 ('20011207', '135'),
 ('20011210', '136'),
 ('20011211', '135'),
 ('20011212', '138'),
 ('20011213', '134'),
 ('20011214', '135'),
 ('20011217', '132'),
 ('20011218', '124'),
 ('20011219', '125'),
 ('20011220', '126'),
 ('20011221', '130'),
 ('20011225', '128'),
 ('20011226', '128'),
 ('20011227', '132'),
 ('20011228', '129'),
 ('20020104', '129'),
 ('20020107', '134'),
 ('20020108', '130'),
 ('20020109', '133'),
 ('20020110', '131'),
 ('20020111', '129'),
 ('20020115', '127'),
 ('20020116', '126'),
 ('20020117', '125'),
 ('20020118', '125'),
 ('20020121', '126'),
 ('20020122', '126'),
 ('20020123', '128'),
 ('20020124', '127'),
 ('20020125', '125'),
 ('20020128', '126'),
 ('20020129', '126'),
 ('20020130', '127'),
 ('20020131', '126'),
 ('20020201', '127'),
 ('20020204', '128'),
 ('20020205', '126'),
 ('20020206', '125'),
 ('20020207', '127'),
 ('20020208', '127'),
 ('20020212', '127'),
 ('20020213', '131'),
 ('20020214', '132'),
 ('20020215', '133'),
 ('20020218', '135'),
 ('20020219', '131'),
 ('20020220', '130'),
 ('20020221', '135'),
 ('20020222', '137'),
 ('20020225', '131'),
 ('20020226', '133'),
 ('20020227', '140'),
 ('20020228', '137'),
 ('20020301', '141'),
 ('20020304', '147'),
 ('20020305', '143'),
 ('20020306', '145'),
 ('20020307', '147'),
 ('20020308', '147'),
 ('20020311', '148'),
 ('20020312', '148'),
 ('20020313', '144'),
 ('20020314', '147'),
 ('20020315', '147'),
 ('20020318', '145'),
 ('20020319', '148'),
 ('20020320', '144'),
 ('20020322', '143'),
 ('20020325', '144'),
 ('20020326', '142'),
 ('20020327', '147'),
 ('20020328', '145'),
 ('20020329', '143'),
 ('20020401', '136'),
 ('20020402', '140'),
 ('20020403', '143'),
 ('20020404', '145'),
 ('20020405', '145'),
 ('20020408', '144'),
 ('20020409', '142'),
 ('20020410', '145'),
 ('20020411', '141'),
 ('20020412', '137'),
 ('20020415', '137'),
 ('20020416', '142'),
 ('20020417', '142'),
 ('20020418', '139'),
 ('20020419', '140'),
 ('20020422', '140'),
 ('20020423', '139'),
 ('20020424', '138'),
 ('20020425', '137'),
 ('20020426', '137'),
 ('20020430', '138'),
 ('20020501', '136'),
 ('20020502', '136'),
 ('20020507', '132'),
 ('20020508', '139'),
 ('20020509', '139'),
 ('20020510', '137'),
 ('20020513', '137'),
 ('20020514', '139'),
 ('20020515', '141'),
 ('20020516', '140'),
 ('20020517', '142'),
 ('20020520', '144'),
 ('20020521', '142'),
 ('20020522', '149'),
 ('20020523', '147'),
 ('20020524', '144'),
 ('20020527', '146'),
 ('20020528', '146'),
 ('20020529', '145'),
 ('20020530', '142'),
 ('20020531', '143'),
 ('20020603', '143'),
 ('20020604', '142'),
 ('20020605', '140'),
 ('20020606', '139'),
 ('20020607', '138'),
 ('20020610', '138'),
 ('20020611', '139'),
 ('20020612', '138'),
 ('20020613', '136'),
 ('20020614', '135'),
 ('20020617', '132'),
 ('20020618', '133'),
 ('20020619', '130'),
 ('20020620', '130'),
 ('20020621', '130'),
 ('20020624', '128'),
 ('20020625', '132'),
 ('20020626', '128'),
 ('20020627', '131'),
 ('20020628', '133'),
 ('20020701', '130'),
 ('20020702', '132'),
 ('20020703', '136'),
 ('20020704', '134'),
 ('20020705', '137'),
 ('20020708', '133'),
 ('20020709', '136'),
 ('20020710', '134'),
 ('20020711', '132'),
 ('20020712', '133'),
 ('20020715', '131'),
 ('20020716', '130'),
 ('20020717', '132'),
 ('20020718', '134'),
 ('20020719', '129'),
 ('20020722', '129'),
 ('20020723', '130'),
 ('20020724', '129'),
 ('20020725', '131'),
 ('20020726', '128'),
 ('20020729', '129'),
 ('20020730', '130'),
 ('20020731', '129'),
 ('20020801', '129'),
 ('20020802', '127'),
 ('20020805', '129'),
 ('20020806', '129'),
 ('20020807', '130'),
 ('20020808', '130'),
 ('20020809', '130'),
 ('20020812', '127'),
 ('20020813', '124'),
 ('20020814', '123'),
 ('20020815', '126'),
 ('20020816', '125'),
 ('20020819', '122'),
 ('20020820', '121'),
 ('20020821', '121'),
 ('20020822', '121'),
 ('20020823', '122'),
 ('20020826', '125'),
 ('20020827', '122'),
 ('20020828', '124'),
 ('20020829', '123'),
 ('20020830', '122'),
 ('20020902', '120'),
 ('20020903', '117'),
 ('20020904', '116'),
 ('20020905', '112'),
 ('20020906', '106'),
 ('20020909', '109'),
 ('20020910', '108'),
 ('20020911', '109'),
 ('20020912', '108'),
 ('20020913', '107'),
 ('20020917', '112'),
 ('20020918', '112'),
 ('20020919', '116'),
 ('20020920', '114'),
 ('20020924', '112'),
 ('20020925', '110'),
 ('20020926', '107'),
 ('20020927', '105'),
 ('20020930', '106'),
 ('20021001', '104'),
 ('20021002', '103'),
 ('20021003', '102'),
 ('20021004', '101'),
 ('20021007', '97'),
 ('20021008', '104'),
 ('20021009', '100'),
 ('20021010', '98'),
 ('20021011', '96'),
 ('20021015', '98'),
 ('20021016', '100'),
 ('20021017', '103'),
 ('20021018', '103'),
 ('20021021', '103'),
 ('20021022', '101'),
 ('20021023', '101'),
 ('20021024', '99'),
 ('20021025', '100'),
 ('20021028', '100'),
 ('20021029', '100'),
 ('20021030', '103'),
 ('20021031', '100'),
 ('20021101', '101'),
 ('20021105', '100'),
 ('20021106', '101'),
 ('20021107', '103'),
 ('20021108', '103'),
 ('20021111', '100'),
 ('20021112', '100'),
 ('20021113', '100'),
 ('20021114', '97'),
 ('20021115', '100'),
 ('20021118', '98'),
 ('20021119', '95'),
 ('20021120', '102'),
 ('20021121', '102'),
 ('20021122', '103'),
 ('20021125', '106'),
 ('20021126', '105'),
 ('20021127', '107'),
 ('20021128', '111'),
 ('20021129', '110'),
 ('20021202', '113'),
 ('20021203', '113'),
 ('20021204', '115'),
 ('20021205', '113'),
 ('20021206', '111'),
 ('20021209', '111'),
 ('20021210', '113'),
 ('20021211', '110'),
 ('20021212', '109'),
 ('20021213', '110'),
 ('20021216', '112'),
 ('20021217', '110'),
 ('20021218', '109'),
 ('20021219', '111'),
 ('20021220', '110'),
 ('20021224', '112'),
 ('20021225', '112'),
 ('20021226', '114'),
 ('20021227', '115'),
 ('20021230', '113'),
 ('20030106', '115'),
 ('20030107', '118'),
 ('20030108', '122'),
 ('20030109', '128'),
 ('20030110', '127'),
 ('20030114', '127'),
 ('20030115', '134'),
 ('20030116', '135'),
 ('20030117', '138'),
 ('20030120', '135'),
 ('20030121', '138'),
 ('20030122', '135'),
 ('20030123', '135'),
 ('20030124', '135'),
 ('20030127', '136'),
 ('20030128', '143'),
 ('20030129', '137'),
 ('20030130', '138'),
 ('20030131', '135'),
 ('20030203', '138'),
 ('20030204', '139'),
 ('20030205', '139'),
 ('20030206', '140'),
 ('20030207', '140'),
 ('20030210', '140'),
 ('20030212', '145'),
 ('20030213', '143'),
 ('20030214', '142'),
 ('20030217', '141'),
 ('20030218', '142'),
 ('20030219', '144'),
 ('20030220', '142'),
 ('20030221', '139'),
 ('20030224', '136'),
 ('20030225', '133'),
 ('20030226', '133'),
 ('20030227', '134'),
 ('20030228', '137'),
 ('20030303', '141'),
 ('20030304', '138'),
 ('20030305', '135'),
 ('20030306', '131'),
 ('20030307', '126'),
 ('20030310', '122'),
 ('20030311', '122'),
 ('20030312', '123'),
 ('20030313', '126'),
 ('20030314', '123'),
 ('20030317', '120'),
 ('20030318', '122'),
 ('20030319', '123'),
 ('20030320', '124'),
 ('20030324', '128'),
 ('20030325', '128'),
 ('20030326', '125'),
 ('20030327', '125'),
 ('20030328', '124'),
 ('20030331', '120'),
 ('20030401', '119'),
 ('20030402', '120'),
 ('20030403', '121'),
 ('20030404', '124'),
 ('20030407', '126'),
 ('20030408', '122'),
 ('20030409', '124'),
 ('20030410', '121'),
 ('20030411', '122'),
 ('20030414', '118'),
 ('20030415', '120'),
 ('20030416', '121'),
 ('20030417', '121'),
 ('20030418', '122'),
 ('20030421', '127'),
 ('20030422', '132'),
 ('20030423', '135'),
 ('20030424', '129'),
 ('20030425', '127'),
 ('20030428', '123'),
 ('20030430', '133'),
 ('20030501', '129'),
 ('20030502', '130'),
 ('20030506', '131'),
 ('20030507', '128'),
 ('20030508', '129'),
 ('20030509', '131'),
 ('20030512', '130'),
 ('20030513', '132'),
 ('20030514', '131'),
 ('20030515', '131'),
 ('20030516', '131'),
 ('20030519', '134'),
 ('20030520', '133'),
 ('20030521', '131'),
 ('20030522', '136'),
 ('20030523', '136'),
 ('20030526', '138'),
 ('20030527', '136'),
 ('20030528', '136'),
 ('20030529', '136'),
 ('20030530', '135'),
 ('20030602', '134'),
 ('20030603', '134'),
 ('20030604', '135'),
 ('20030605', '143'),
 ('20030606', '141'),
 ('20030609', '141'),
 ('20030610', '145'),
 ('20030611', '144'),
 ('20030612', '142'),
 ('20030613', '143'),
 ('20030616', '148'),
 ('20030617', '148'),
 ('20030618', '149'),
 ('20030619', '148'),
 ('20030620', '152'),
 ('20030623', '155'),
 ('20030624', '152'),
 ('20030625', '152'),
 ('20030626', '163'),
 ('20030627', '169'),
 ('20030630', '165'),
 ('20030701', '168'),
 ('20030702', '168'),
 ('20030703', '159'),
 ('20030704', '161'),
 ('20030707', '161'),
 ('20030708', '158'),
 ('20030709', '161'),
 ('20030710', '164'),
 ('20030711', '161'),
 ('20030714', '161'),
 ('20030715', '160'),
 ('20030716', '157'),
 ('20030717', '148'),
 ('20030718', '147'),
 ('20030722', '150'),
 ('20030723', '152'),
 ('20030724', '152'),
 ('20030725', '153'),
 ('20030728', '156'),
 ('20030729', '155'),
 ('20030730', '153'),
 ('20030731', '151'),
 ('20030801', '156'),
 ('20030804', '160'),
 ('20030805', '157'),
 ('20030806', '156'),
 ('20030807', '154'),
 ('20030808', '152'),
 ('20030811', '153'),
 ('20030812', '153'),
 ('20030813', '153'),
 ('20030814', '160'),
 ('20030815', '162'),
 ('20030818', '170'),
 ('20030819', '166'),
 ('20030820', '168'),
 ('20030821', '169'),
 ('20030822', '196'),
 ('20030825', '219'),
 ('20030826', '215'),
 ('20030827', '214'),
 ('20030828', '207'),
 ('20030829', '208'),
 ('20030901', '209'),
 ('20030902', '202'),
 ('20030903', '221'),
 ('20030904', '213'),
 ('20030905', '207'),

In [108]:
comp_code = '1930'   # an example with missing values

import pandas as pd
dates = [x[0] for x in kabuka[comp_code]]
values = [float(x[1]) for x in kabuka[comp_code]]

data = pd.DataFrame({"value": values})
data.index = pd.to_datetime(dates)

data
#hoge = data[data.columns[0]][pd.to_datetime("20000107"):pd.to_datetime("20000109")]

            value
2000-01-04  300.0
2000-01-05  251.0
2000-01-06  270.0
2000-01-07  265.0
2000-01-11    0.0
2000-01-12  270.0
2000-01-13  265.0
2000-01-14  265.0
2000-01-17  271.0
2000-01-18  311.0
2000-01-19  276.0
2000-01-20  286.0
2000-01-21  280.0
2000-01-24  300.0
2000-01-25  300.0
2000-01-26    0.0
2000-01-27  300.0
2000-01-28    0.0
2000-01-31  270.0
2000-02-01  265.0
2000-02-02  256.0
2000-02-03    0.0
2000-02-04  260.0
2000-02-07  260.0
2000-02-08  260.0
2000-02-09  256.0
2000-02-10  255.0
2000-02-14    0.0
2000-02-15  231.0
2000-02-16  234.0
...           ...
2010-11-17  212.0
2010-11-18  215.0
2010-11-19  215.0
2010-11-22  217.0
2010-11-24  213.0
2010-11-25  213.0
2010-11-26  210.0
2010-11-29  209.0
2010-11-30  210.0
2010-12-01  207.0
2010-12-02  213.0
2010-12-03  210.0
2010-12-06  212.0
2010-12-07  208.0
2010-12-08  206.0
2010-12-09  209.0
2010-12-10  209.0
2010-12-13  213.0
2010-12-14  215.0
2010-12-15  214.0
2010-12-16  214.0
2010-12-17  212.0
2010-12-20  212.0
2010-12-21  215.0
2010-12-22  216.0
2010-12-24  216.0
2010-12-27  218.0
2010-12-28  216.0
2010-12-29  217.0
2010-12-30  216.0

[2702 rows x 1 columns]

与えられた範囲に基づいて必要な期間を計算し、同じ日付のデータだけをdata, marketから抽出したい

期待値には(-246, -30)の範囲を、arには(-1, 1)の範囲を使用する

プレスリリースの日付が株価データにない場合は、その日付より後で株価データの存在する最も近い日付を0とする

-> 先に使用する範囲のデータを抽出してからreturnを計算しないと、dataは欠損値ありでかなり昔との比較によるreturnなのにmarketは前日との比較、みたいなことになってしまう。

In [231]:
def determine_interval(data, market, date):   # DataFrame, DataFrame, datetime
    er_start= -5#-246 - 1
    er_end = -2#-30 
    #ar_start = -1 - 1
    #ar_end = 1
    
    data_val = data[data.columns[0]]
    market_val = market[market.columns[0]]
    
    ## 指定された日付がデータの範囲に収まっているか判定
    max_date = max(data.index)
    while (max_date not in data_val or data_val[max_date] == 0.):
        max_date = max_date - pd.offsets.Day(1)
    min_date = min(data.index)
    while (min_date not in data_val or data_val[min_date] == 0.):
        min_date = min_date + pd.offsets.Day(1)
    if date < min_date or date > max_date:
        return   # OutOfIndex
    
    ## 与えられたdate以降の日付で、株価データが存在するような最も近い日付を求める
    while (date not in data_val or data_val[date] == 0.):
        date = date + pd.offsets.Day(1) 
        if date > max_date:
            return 
    origin = date
    #print("Origin:", date)
    
    ## 計算に使う範囲の(有効な)株価データを抽出 -> リファクタリング: 先に株価0のエントリーを除去してから連続的に区間を抽出するだけで良い
    er_data = []
    er_market = []
    ar_data = []
    ar_market = []
    
    count = 0
    date = origin
    while (er_end < count):
        date = date - pd.offsets.Day(1)
        if date < min_date:
            return
        if date in data_val and data_val[date] >  0.:
            count -= 1
    #print("Er_end:", date)
    er_data.append(data_val[date])
    er_market.append(market_val[date])
    while (er_start < count):
        date = date - pd.offsets.Day(1)
        if date < min_date:
            return
        if date  in data_val and data_val[date] >  0.:
            er_data.append(data_val[date])
            er_market.append(market_val[date])
            count -= 1
    #print("Er_start:", date)
    er_data.reverse()
    er_market.reverse()
    #print(er_data, er_market)
    
    date = origin - pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date - pd.offsets.Day(1) 
        if date < min_date:
            return
    ar_data.append(data_val[date])    # at -1
    ar_market.append(market_val[date])
    date = date - pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date - pd.offsets.Day(1) 
        if date < min_date:
            return
    ar_data.append(data_val[date])   # at -2
    ar_market.append(market_val[date])
    ar_data.reverse()
    ar_market.reverse()
    
    ar_data.append(data_val[origin])   # at 0
    ar_market.append(market_val[origin])
    date = origin + pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date + pd.offsets.Day(1) 
        if date > max_date:
            return
    ar_data.append(data_val[date])   # at +1
    ar_market.append(market_val[date])
    #print(ar_data, ar_market)
    
    import numpy as np
    return (np.array(er_data), np.array(er_market), np.array(ar_data), np.array(ar_market))

In [232]:
ed, em, ad, am = determine_interval(data, market, pd.to_datetime("20000125"))

In [245]:
# data: arを計算したい企業の株価時系列データ
# market: 株価指数時系列データ
# start_period [end_period]: 期待値の計算に使う期間の開始[終了]日時
# start_window [end_window]: arを計算したい期間の開始[終了]日時

# 欠損値はこれに渡す前に整形する？dataで0になっているところをdata, market両方から除去とか
# その場合、*_periodの値も調整してから渡す必要がある

def market_return(er_data, er_market, ar_data, ar_market):
    import numpy as np
    import pandas as pd
    from scipy import stats
    from datetime import datetime
    
    #print("DATA:", ar_data)
    #print("MARKET:", ar_market)
        
    def calculate_returns(d):   # np.array of stock values
        dr = np.zeros(shape=d.shape)
        dr[1:] = d[1:] / d[0:-1]# - 1   # why -1?
        return dr[1:]
    
    # 1. Linear Regression: On the estimation_period
    er_data = calculate_returns(er_data)
    er_market = calculate_returns(er_market)
    ar_data = calculate_returns(ar_data)
    ar_market = calculate_returns(ar_market)
    
    #print("")
    #print("RETURN(DATA):", ar_data)
    #print("RETURN(MARKET):", ar_market)
    
    #c_name = dr_data.columns[0]
    #x =  dr_market[c_name][start_period:end_period]
    #y = dr_data[c_name][start_period:end_period]
    slope, intercept, r_value, p_value, std_error = stats.linregress(er_market, er_data)
    er_reg = lambda x: x * slope + intercept
    
    #print("")
    #print("REG(DATA):", er_data)
    #print("REG(MARKET):", er_market)
    #print("REG: DATA = " + str(slope) + "MARKET + " + str(intercept))
    #print("")

    # 2. Analysis on the event window
    # Expexted Return:
    er = er_reg(ar_market)
    #er.name = 'Expected return'
    # Abnormal return: Return of the data - expected return
    ar = ar_data - er
    #ar.name = 'Abnormal return'
    # Cumulative abnormal return
    car = ar.cumsum()
    #car.name = 'Cum abnormal return'
    
    #print("ER:", er)
    #print("AR:", ar)
    #print("CAR:", car)
    return car[-1]

In [244]:
market_return(ed, em, ad, am)

DATA: [ 280.  300.  300.  300.]
MARKET: [ 1627.14  1647.96  1632.57  1685.9 ]

RETURN(DATA): [ 1.07142857  1.          1.        ]
RETURN(MARKET): [ 1.01279546  0.99066118  1.03266629]

REG(DATA): [ 0.88745981  1.03623188  0.97902098]
REG(MARKET): [ 0.97925371  1.00112182  0.9963444 ]
REG: DATA = 6.41954137194MARKET + -5.40215468335

ER: [ 1.09952765  0.95743575  1.22708927]
AR: [-0.02809908  0.04256425 -0.22708927]
CAR: [-0.02809908  0.01446516 -0.21262411]

-0.21262410619195715

### Cumulative abnormal returnの計算例

In [248]:
## Example
ed, em, ad, am = determine_interval(data, market, pd.to_datetime("20000125"))
car = market_return(ed, em, ad, am)
print(car)

-0.212624106192

あとは全部のプレスリリースについてアブノーマルリターンを計算して、基本統計量の算出、できれば学習器を生成したい。

複数の企業がヒットしたプレスリリースは、それぞれ別々に扱うことにする。

In [250]:
def load_kabuka(code):
    import pandas as pd
    dates = [x[0] for x in kabuka[comp_code]]
    values = [float(x[1]) for x in kabuka[comp_code]]

    data = pd.DataFrame({"value": values})
    data.index = pd.to_datetime(dates)
    return data

In [257]:
car = {}
for articleid, data in matching.items():        
    date, codes, names = data
    for code in codes:
        kabuka_data = load_kabuka(code)
        ret = determine_interval(kabuka_data, market, pd.to_datetime(date))
        if ret == None:
            continue
        ed, em, ad, am = ret
        car[(articleid, code)] = market_return(ed, em, ad, am)

In [258]:
len(car)

70905

In [260]:
car[("NIKPRLRSP038060_07012003", '7951')]

-0.025903727002708599

In [261]:
with open("car", 'w') as f:
    for key, v in car.items():
        articleid, code = key
        f.write('\t'.join([articleid, code, v]))
        f.write('\n')

TypeError: sequence item 2: expected str instance, numpy.float64 found