In [3]:
data_dir = "data/"
lc_fname = "listed_company"
#pr_fname = "test.csv"
#pr_fname = "pressrelease_all.csv"
matching_fname = "matchings"
kabuka_fname = "kabuka_tse1"
market_fname = "market_tse1"

In [4]:
lc_code = {}
with open(data_dir + lc_fname, 'r') as f:
    for line in f:
        data = line.strip().split('\t')
        lc_code[data[0]] = data[2]
        
#print(lc_code)

In [5]:
matching = {}
with open(matching_fname, 'r') as f:
    for line in f:
        data = line.strip().split('\t')
        comp = data[2].strip().split(' ')
        comp_code = [lc_code[x] for x in comp]
        matching[data[0]] = (data[1], comp_code, comp)
        
#print(matching)
# {articleid : (date, [code], [name])}

In [6]:
# TOPIXデータの読み込み

topix = []
with open(data_dir + market_fname, 'r') as f:
    for line in f:
        data = line.strip().split(',')
        #comp_code = data[0]
        for x in data[1:]:
            date, value = x.split(':')
            topix.append((date, value))
            
import pandas as pd
dates = [x[0] for x in topix]
values = [float(x[1]) for x in topix]

market = pd.DataFrame({"value": values})
market.index = pd.to_datetime(dates)

In [99]:
market

              value
2000-01-04  1717.47
2000-01-05  1651.84
2000-01-06  1609.59
2000-01-07  1599.01
2000-01-11  1678.82
2000-01-12  1656.92
2000-01-13  1657.97
2000-01-14  1648.24
2000-01-17  1681.97
2000-01-18  1665.84
2000-01-19  1631.28
2000-01-20  1633.11
2000-01-21  1627.14
2000-01-24  1647.96
2000-01-25  1632.57
2000-01-26  1664.09
2000-01-27  1685.90
2000-01-28  1702.61
2000-01-31  1707.96
2000-02-01  1697.15
2000-02-02  1711.86
2000-02-03  1729.48
2000-02-04  1741.22
2000-02-07  1754.78
2000-02-08  1737.55
2000-02-09  1747.83
2000-02-10  1729.47
2000-02-14  1717.41
2000-02-15  1690.14
2000-02-16  1691.12
...             ...
2010-11-17   850.30
2010-11-18   868.81
2010-11-19   869.52
2010-11-22   875.48
2010-11-24   866.57
2010-11-25   869.81
2010-11-26   866.81
2010-11-29   874.59
2010-11-30   860.94
2010-12-01   866.07
2010-12-02   877.21
2010-12-03   879.22
2010-12-06   881.41
2010-12-07   879.10
2010-12-08   887.39
2010-12-09   891.60
2010-12-10   888.22
2010-12-13   897.40
2010-12-14   901.89
2010-12-15   902.42
2010-12-16   903.84
2010-12-17   903.14
2010-12-20   898.55
2010-12-21   906.21
2010-12-22   905.78
2010-12-24   901.66
2010-12-27   904.68
2010-12-28   902.83
2010-12-29   908.01
2010-12-30   898.80

[2702 rows x 1 columns]

In [7]:
# 株価データの読み込み、欠損値がある企業はどうする？

from collections import defaultdict

kabuka = defaultdict(list)
with open(data_dir + kabuka_fname, 'r') as f:
    for line in f:
        data = line.strip().split(',')
        comp_code = data[0]
        for x in data[1:]:
            date, value = x.split(':')
            kabuka[comp_code].append((date, value))

In [28]:
comp_code = '1930'   # an example with missing values

import pandas as pd
dates = [x[0] for x in kabuka[comp_code]]
values = [float(x[1]) for x in kabuka[comp_code]]

data = pd.DataFrame({"value": values})
data.index = pd.to_datetime(dates)

data
#hoge = data[data.columns[0]][pd.to_datetime("20000107"):pd.to_datetime("20000109")]

            value
2000-01-04  300.0
2000-01-05  251.0
2000-01-06  270.0
2000-01-07  265.0
2000-01-11    0.0
2000-01-12  270.0
2000-01-13  265.0
2000-01-14  265.0
2000-01-17  271.0
2000-01-18  311.0
2000-01-19  276.0
2000-01-20  286.0
2000-01-21  280.0
2000-01-24  300.0
2000-01-25  300.0
2000-01-26    0.0
2000-01-27  300.0
2000-01-28    0.0
2000-01-31  270.0
2000-02-01  265.0
2000-02-02  256.0
2000-02-03    0.0
2000-02-04  260.0
2000-02-07  260.0
2000-02-08  260.0
2000-02-09  256.0
2000-02-10  255.0
2000-02-14    0.0
2000-02-15  231.0
2000-02-16  234.0
...           ...
2010-11-17  212.0
2010-11-18  215.0
2010-11-19  215.0
2010-11-22  217.0
2010-11-24  213.0
2010-11-25  213.0
2010-11-26  210.0
2010-11-29  209.0
2010-11-30  210.0
2010-12-01  207.0
2010-12-02  213.0
2010-12-03  210.0
2010-12-06  212.0
2010-12-07  208.0
2010-12-08  206.0
2010-12-09  209.0
2010-12-10  209.0
2010-12-13  213.0
2010-12-14  215.0
2010-12-15  214.0
2010-12-16  214.0
2010-12-17  212.0
2010-12-20  212.0
2010-12-21  215.0
2010-12-22  216.0
2010-12-24  216.0
2010-12-27  218.0
2010-12-28  216.0
2010-12-29  217.0
2010-12-30  216.0

[2702 rows x 1 columns]

与えられた範囲に基づいて必要な期間を計算し、同じ日付のデータだけをdata, marketから抽出したい

期待値には(-246, -30)の範囲を、arには(-1, 1)の範囲を使用する

プレスリリースの日付が株価データにない場合は、その日付より後で株価データの存在する最も近い日付を0とする

-> 先に使用する範囲のデータを抽出してからreturnを計算しないと、dataは欠損値ありでかなり昔との比較によるreturnなのにmarketは前日との比較、みたいなことになってしまう。

In [49]:
def determine_interval(data, market, date):   # DataFrame, DataFrame, datetime
    er_start= -246 - 1
    er_end = -30 
    #ar_start = -1 - 1
    #ar_end = 1
    
    data_val = data[data.columns[0]]
    market_val = market[market.columns[0]]
    
    ## 指定された日付がデータの範囲に収まっているか判定
    max_date = max(data.index)
    while (max_date not in data_val or data_val[max_date] == 0.):
        max_date = max_date - pd.offsets.Day(1)
    min_date = min(data.index)
    while (min_date not in data_val or data_val[min_date] == 0.):
        min_date = min_date + pd.offsets.Day(1)
    if date < min_date or date > max_date:
        return   # OutOfIndex
    
    ## 与えられたdate以降の日付で、株価データが存在するような最も近い日付を求める
    while (date not in data_val or data_val[date] == 0.):
        date = date + pd.offsets.Day(1) 
        if date > max_date:
            return 
    origin = date
    #print("Origin:", date)
    
    ## 計算に使う範囲の(有効な)株価データを抽出 -> リファクタリング: 先に株価0のエントリーを除去してから連続的に区間を抽出するだけで良い
    er_data = []
    er_market = []
    ar_data = []
    ar_market = []
    
    count = 0
    date = origin
    while (er_end < count):
        date = date - pd.offsets.Day(1)
        if date < min_date:
            return
        if date in data_val and data_val[date] >  0.:
            count -= 1
    #print("Er_end:", date)
    er_data.append(data_val[date])
    er_market.append(market_val[date])
    while (er_start < count):
        date = date - pd.offsets.Day(1)
        if date < min_date:
            return
        if date  in data_val and data_val[date] >  0.:
            er_data.append(data_val[date])
            er_market.append(market_val[date])
            count -= 1
    #print("Er_start:", date)
    er_data.reverse()
    er_market.reverse()
    #print(er_data, er_market)
    
    date = origin - pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date - pd.offsets.Day(1) 
        if date < min_date:
            return
    ar_data.append(data_val[date])    # at -1
    ar_market.append(market_val[date])
    date = date - pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date - pd.offsets.Day(1) 
        if date < min_date:
            return
    ar_data.append(data_val[date])   # at -2
    ar_market.append(market_val[date])
    ar_data.reverse()
    ar_market.reverse()
    
    ar_data.append(data_val[origin])   # at 0
    ar_market.append(market_val[origin])
    date = origin + pd.offsets.Day(1)
    while (date not in data_val or data_val[date] == 0.):
        date = date + pd.offsets.Day(1) 
        if date > max_date:
            return
    ar_data.append(data_val[date])   # at +1
    ar_market.append(market_val[date])
    #print(ar_data, ar_market)
    
    import numpy as np
    return (np.array(er_data), np.array(er_market), np.array(ar_data), np.array(ar_market))

In [29]:
ed, em, ad, am = determine_interval(data, market, pd.to_datetime("20000125"))

Origin: 2000-01-25 00:00:00
Er_end: 2000-01-21 00:00:00
Er_start: 2000-01-18 00:00:00
[311.0, 276.0, 286.0, 280.0] [1665.8399999999999, 1631.28, 1633.1099999999999, 1627.1400000000001]
[280.0, 300.0, 300.0, 300.0] [1627.1400000000001, 1647.96, 1632.5699999999999, 1685.9000000000001]

In [9]:
# data: arを計算したい企業の株価時系列データ
# market: 株価指数時系列データ
# start_period [end_period]: 期待値の計算に使う期間の開始[終了]日時
# start_window [end_window]: arを計算したい期間の開始[終了]日時

# 欠損値はこれに渡す前に整形する？dataで0になっているところをdata, market両方から除去とか
# その場合、*_periodの値も調整してから渡す必要がある

def market_return(er_data, er_market, ar_data, ar_market):
    import numpy as np
    import pandas as pd
    from scipy import stats
    from datetime import datetime
    
    #print("DATA:", ar_data)
    #print("MARKET:", ar_market)
        
    def calculate_returns(d):   # np.array of stock values
        dr = np.zeros(shape=d.shape)
        dr[1:] = d[1:] / d[0:-1]# - 1   # why -1?
        return dr[1:]
    
    # 1. Linear Regression: On the estimation_period
    er_data = calculate_returns(er_data)
    er_market = calculate_returns(er_market)
    ar_data = calculate_returns(ar_data)
    ar_market = calculate_returns(ar_market)
    
    #print("")
    #print("RETURN(DATA):", ar_data)
    #print("RETURN(MARKET):", ar_market)
    
    #c_name = dr_data.columns[0]
    #x =  dr_market[c_name][start_period:end_period]
    #y = dr_data[c_name][start_period:end_period]
    slope, intercept, r_value, p_value, std_error = stats.linregress(er_market, er_data)
    er_reg = lambda x: x * slope + intercept
    
    #print("")
    #print("REG(DATA):", er_data)
    #print("REG(MARKET):", er_market)
    #print("REG: DATA = " + str(slope) + "MARKET + " + str(intercept))
    #print("")

    # 2. Analysis on the event window
    # Expexted Return:
    er = er_reg(ar_market)
    #er.name = 'Expected return'
    # Abnormal return: Return of the data - expected return
    ar = ar_data - er
    #ar.name = 'Abnormal return'
    # Cumulative abnormal return
    car = ar.cumsum()
    #car.name = 'Cum abnormal return'
    
    #print("ER:", er)
    #print("AR:", ar)
    #print("CAR:", car)
    return car[-1]

In [244]:
market_return(ed, em, ad, am)

DATA: [ 280.  300.  300.  300.]
MARKET: [ 1627.14  1647.96  1632.57  1685.9 ]

RETURN(DATA): [ 1.07142857  1.          1.        ]
RETURN(MARKET): [ 1.01279546  0.99066118  1.03266629]

REG(DATA): [ 0.88745981  1.03623188  0.97902098]
REG(MARKET): [ 0.97925371  1.00112182  0.9963444 ]
REG: DATA = 6.41954137194MARKET + -5.40215468335

ER: [ 1.09952765  0.95743575  1.22708927]
AR: [-0.02809908  0.04256425 -0.22708927]
CAR: [-0.02809908  0.01446516 -0.21262411]

-0.21262410619195715

### Cumulative abnormal returnの計算例

In [52]:
## Example
ed, em, ad, am = determine_interval(data, market, pd.to_datetime("20000125"))
car = market_return(ed, em, ad, am)
print(car)

AttributeError: 'tuple' object has no attribute 'columns'

あとは全部のプレスリリースについてアブノーマルリターンを計算して、基本統計量の算出、できれば学習器を生成したい。

複数の企業がヒットしたプレスリリースは、それぞれ別々に扱うことにする。

In [53]:
def load_kabuka(code):
    import pandas as pd
    dates = [x[0] for x in kabuka[code]]
    values = [float(x[1]) for x in kabuka[code]]

    data = pd.DataFrame({"value": values})
    data.index = pd.to_datetime(dates)
    return data

In [54]:
count = 0
car = {}
for articleid, data in matching.items():
    #print(articleid)
    #count += 1
    #if count > 10:
    #    break
    date, codes, names = data
    #print(date)
    for code in codes:
        #print(code)
        if code not in kabuka:
            #print("no code")
            continue
        kabuka_data = load_kabuka(code)
        #print(kabuka_data)
        ret = determine_interval(kabuka_data, market, pd.to_datetime(date))
        if ret == None:
            #print("no kabuka")
            continue
        ed, em, ad, am = ret
        car[(articleid, code)] = market_return(ed, em, ad, am)   # エイリアスはここで縮約されるか
        #print(car[(articleid, code)])
#print(car)

In [25]:
kabuka['7951']

[('20000104', '655'),
 ('20000105', '661'),
 ('20000106', '661'),
 ('20000107', '678'),
 ('20000111', '681'),
 ('20000112', '687'),
 ('20000113', '708'),
 ('20000114', '711'),
 ('20000117', '729'),
 ('20000118', '727'),
 ('20000119', '723'),
 ('20000120', '719'),
 ('20000121', '700'),
 ('20000124', '711'),
 ('20000125', '708'),
 ('20000126', '711'),
 ('20000127', '710'),
 ('20000128', '719'),
 ('20000131', '779'),
 ('20000201', '757'),
 ('20000202', '750'),
 ('20000203', '750'),
 ('20000204', '730'),
 ('20000207', '740'),
 ('20000208', '750'),
 ('20000209', '777'),
 ('20000210', '808'),
 ('20000214', '808'),
 ('20000215', '765'),
 ('20000216', '807'),
 ('20000217', '777'),
 ('20000218', '760'),
 ('20000221', '760'),
 ('20000222', '798'),
 ('20000223', '764'),
 ('20000224', '760'),
 ('20000225', '767'),
 ('20000228', '772'),
 ('20000229', '753'),
 ('20000301', '755'),
 ('20000302', '756'),
 ('20000303', '766'),
 ('20000306', '780'),
 ('20000307', '776'),
 ('20000308', '753'),
 ('20000309', '772'),
 ('20000310', '808'),
 ('20000313', '837'),
 ('20000314', '777'),
 ('20000315', '788'),
 ('20000316', '775'),
 ('20000317', '762'),
 ('20000321', '770'),
 ('20000322', '790'),
 ('20000323', '800'),
 ('20000324', '819'),
 ('20000327', '879'),
 ('20000328', '856'),
 ('20000329', '833'),
 ('20000330', '816'),
 ('20000331', '832'),
 ('20000403', '850'),
 ('20000404', '840'),
 ('20000405', '851'),
 ('20000406', '860'),
 ('20000407', '838'),
 ('20000410', '859'),
 ('20000411', '857'),
 ('20000412', '859'),
 ('20000413', '856'),
 ('20000414', '851'),
 ('20000417', '820'),
 ('20000418', '782'),
 ('20000419', '767'),
 ('20000420', '753'),
 ('20000421', '710'),
 ('20000424', '765'),
 ('20000425', '737'),
 ('20000426', '730'),
 ('20000427', '728'),
 ('20000428', '732'),
 ('20000501', '741'),
 ('20000502', '790'),
 ('20000508', '822'),
 ('20000509', '822'),
 ('20000510', '826'),
 ('20000511', '811'),
 ('20000512', '831'),
 ('20000515', '847'),
 ('20000516', '858'),
 ('20000517', '865'),
 ('20000518', '864'),
 ('20000519', '848'),
 ('20000522', '858'),
 ('20000523', '850'),
 ('20000524', '812'),
 ('20000525', '818'),
 ('20000526', '900'),
 ('20000529', '935'),
 ('20000530', '943'),
 ('20000531', '980'),
 ('20000601', '1003'),
 ('20000602', '990'),
 ('20000605', '1004'),
 ('20000606', '1040'),
 ('20000607', '1068'),
 ('20000608', '1065'),
 ('20000609', '1040'),
 ('20000612', '1104'),
 ('20000613', '1110'),
 ('20000614', '1120'),
 ('20000615', '1073'),
 ('20000616', '1081'),
 ('20000619', '1064'),
 ('20000620', '1050'),
 ('20000621', '1080'),
 ('20000622', '1045'),
 ('20000623', '1043'),
 ('20000626', '1085'),
 ('20000627', '1167'),
 ('20000628', '1152'),
 ('20000629', '1159'),
 ('20000630', '1159'),
 ('20000703', '1197'),
 ('20000704', '1150'),
 ('20000705', '1145'),
 ('20000706', '1134'),
 ('20000707', '1101'),
 ('20000710', '1136'),
 ('20000711', '1136'),
 ('20000712', '1092'),
 ('20000713', '1032'),
 ('20000714', '1084'),
 ('20000717', '1110'),
 ('20000718', '1062'),
 ('20000719', '1071'),
 ('20000721', '1055'),
 ('20000724', '1031'),
 ('20000725', '1049'),
 ('20000726', '1009'),
 ('20000727', '995'),
 ('20000728', '1000'),
 ('20000731', '980'),
 ('20000801', '996'),
 ('20000802', '1010'),
 ('20000803', '965'),
 ('20000804', '1002'),
 ('20000807', '1039'),
 ('20000808', '1008'),
 ('20000809', '1022'),
 ('20000810', '1039'),
 ('20000811', '1069'),
 ('20000814', '1025'),
 ('20000815', '1038'),
 ('20000816', '1033'),
 ('20000817', '1020'),
 ('20000818', '1009'),
 ('20000821', '986'),
 ('20000822', '991'),
 ('20000823', '978'),
 ('20000824', '982'),
 ('20000825', '981'),
 ('20000828', '963'),
 ('20000829', '958'),
 ('20000830', '947'),
 ('20000831', '937'),
 ('20000901', '930'),
 ('20000904', '920'),
 ('20000905', '894'),
 ('20000906', '899'),
 ('20000907', '877'),
 ('20000908', '918'),
 ('20000911', '909'),
 ('20000912', '930'),
 ('20000913', '985'),
 ('20000914', '973'),
 ('20000918', '949'),
 ('20000919', '929'),
 ('20000920', '986'),
 ('20000921', '955'),
 ('20000922', '939'),
 ('20000925', '922'),
 ('20000926', '931'),
 ('20000927', '931'),
 ('20000928', '901'),
 ('20000929', '907'),
 ('20001002', '911'),
 ('20001003', '914'),
 ('20001004', '922'),
 ('20001005', '938'),
 ('20001006', '920'),
 ('20001010', '902'),
 ('20001011', '897'),
 ('20001012', '941'),
 ('20001013', '900'),
 ('20001016', '911'),
 ('20001017', '871'),
 ('20001018', '864'),
 ('20001019', '864'),
 ('20001020', '880'),
 ('20001023', '916'),
 ('20001024', '890'),
 ('20001025', '898'),
 ('20001026', '945'),
 ('20001027', '930'),
 ('20001030', '946'),
 ('20001031', '940'),
 ('20001101', '952'),
 ('20001102', '936'),
 ('20001106', '1018'),
 ('20001107', '986'),
 ('20001108', '1038'),
 ('20001109', '1001'),
 ('20001110', '1014'),
 ('20001113', '965'),
 ('20001114', '990'),
 ('20001115', '1007'),
 ('20001116', '978'),
 ('20001117', '998'),
 ('20001120', '999'),
 ('20001121', '985'),
 ('20001122', '969'),
 ('20001124', '1025'),
 ('20001127', '1030'),
 ('20001128', '1025'),
 ('20001129', '1049'),
 ('20001130', '1125'),
 ('20001201', '1139'),
 ('20001204', '1130'),
 ('20001205', '1080'),
 ('20001206', '1051'),
 ('20001207', '1050'),
 ('20001208', '1122'),
 ('20001211', '1145'),
 ('20001212', '1170'),
 ('20001213', '1176'),
 ('20001214', '1149'),
 ('20001215', '1110'),
 ('20001218', '1130'),
 ('20001219', '1082'),
 ('20001220', '1059'),
 ('20001221', '1027'),
 ('20001222', '1037'),
 ('20001225', '1130'),
 ('20001226', '1100'),
 ('20001227', '1100'),
 ('20001228', '1129'),
 ('20001229', '1120'),
 ('20010104', '1100'),
 ('20010105', '1106'),
 ('20010109', '1091'),
 ('20010110', '1046'),
 ('20010111', '1028'),
 ('20010112', '1057'),
 ('20010115', '1058'),
 ('20010116', '1050'),
 ('20010117', '1086'),
 ('20010118', '1105'),
 ('20010119', '1145'),
 ('20010122', '1142'),
 ('20010123', '1176'),
 ('20010124', '1166'),
 ('20010125', '1178'),
 ('20010126', '1181'),
 ('20010129', '1221'),
 ('20010130', '1234'),
 ('20010131', '1235'),
 ('20010201', '1236'),
 ('20010202', '1258'),
 ('20010205', '1209'),
 ('20010206', '1189'),
 ('20010207', '1205'),
 ('20010208', '1240'),
 ('20010209', '1277'),
 ('20010213', '1252'),
 ('20010214', '1244'),
 ('20010215', '1317'),
 ('20010216', '1301'),
 ('20010219', '1284'),
 ('20010220', '1326'),
 ('20010221', '1322'),
 ('20010222', '1291'),
 ('20010223', '1319'),
 ('20010226', '1315'),
 ('20010227', '1340'),
 ('20010228', '1378'),
 ('20010301', '1365'),
 ('20010302', '1295'),
 ('20010305', '1355'),
 ('20010306', '1350'),
 ('20010307', '1340'),
 ('20010308', '1331'),
 ('20010309', '1360'),
 ('20010312', '1327'),
 ('20010313', '1323'),
 ('20010314', '1318'),
 ('20010315', '1380'),
 ('20010316', '1321'),
 ('20010319', '1350'),
 ('20010321', '1450'),
 ('20010322', '1426'),
 ('20010323', '1395'),
 ('20010326', '1468'),
 ('20010327', '1425'),
 ('20010328', '1471'),
 ('20010329', '1361'),
 ('20010330', '1318'),
 ('20010402', '1275'),
 ('20010403', '1280'),
 ('20010404', '1334'),
 ('20010405', '1287'),
 ('20010406', '1276'),
 ('20010409', '1236'),
 ('20010410', '1192'),
 ('20010411', '1236'),
 ('20010412', '1239'),
 ('20010413', '1215'),
 ('20010416', '1192'),
 ('20010417', '1151'),
 ('20010418', '1254'),
 ('20010419', '1230'),
 ('20010420', '1211'),
 ('20010423', '1211'),
 ('20010424', '1200'),
 ('20010425', '1231'),
 ('20010426', '1245'),
 ('20010427', '1255'),
 ('20010501', '1300'),
 ('20010502', '1280'),
 ('20010507', '1273'),
 ('20010508', '1240'),
 ('20010509', '1218'),
 ('20010510', '1212'),
 ('20010511', '1211'),
 ('20010514', '1231'),
 ('20010515', '1266'),
 ('20010516', '1226'),
 ('20010517', '1274'),
 ('20010518', '1258'),
 ('20010521', '1263'),
 ('20010522', '1253'),
 ('20010523', '1237'),
 ('20010524', '1231'),
 ('20010525', '1210'),
 ('20010528', '1240'),
 ('20010529', '1261'),
 ('20010530', '1261'),
 ('20010531', '1238'),
 ('20010601', '1220'),
 ('20010604', '1229'),
 ('20010605', '1196'),
 ('20010606', '1186'),
 ('20010607', '1195'),
 ('20010608', '1202'),
 ('20010611', '1171'),
 ('20010612', '1160'),
 ('20010613', '1221'),
 ('20010614', '1191'),
 ('20010615', '1236'),
 ('20010618', '1222'),
 ('20010619', '1210'),
 ('20010620', '1216'),
 ('20010621', '1234'),
 ('20010622', '1243'),
 ('20010625', '1220'),
 ('20010626', '1237'),
 ('20010627', '1250'),
 ('20010628', '1239'),
 ('20010629', '1257'),
 ('20010702', '1233'),
 ('20010703', '1267'),
 ('20010704', '1225'),
 ('20010705', '1231'),
 ('20010706', '1213'),
 ('20010709', '1214'),
 ('20010710', '1200'),
 ('20010711', '1193'),
 ('20010712', '1225'),
 ('20010713', '1207'),
 ('20010716', '1206'),
 ('20010717', '1219'),
 ('20010718', '1202'),
 ('20010719', '1200'),
 ('20010723', '1187'),
 ('20010724', '1236'),
 ('20010725', '1204'),
 ('20010726', '1218'),
 ('20010727', '1224'),
 ('20010730', '1205'),
 ('20010731', '1246'),
 ('20010801', '1221'),
 ('20010802', '1282'),
 ('20010803', '1270'),
 ('20010806', '1289'),
 ('20010807', '1325'),
 ('20010808', '1266'),
 ('20010809', '1222'),
 ('20010810', '1268'),
 ('20010813', '1260'),
 ('20010814', '1307'),
 ('20010815', '1290'),
 ('20010816', '1231'),
 ('20010817', '1238'),
 ('20010820', '1223'),
 ('20010821', '1239'),
 ('20010822', '1274'),
 ('20010823', '1240'),
 ('20010824', '1281'),
 ('20010827', '1301'),
 ('20010828', '1260'),
 ('20010829', '1265'),
 ('20010830', '1265'),
 ('20010831', '1207'),
 ('20010903', '1221'),
 ('20010904', '1235'),
 ('20010905', '1239'),
 ('20010906', '1215'),
 ('20010907', '1194'),
 ('20010910', '1146'),
 ('20010911', '1146'),
 ('20010912', '1047'),
 ('20010913', '1000'),
 ('20010914', '980'),
 ('20010917', '945'),
 ('20010918', '945'),
 ('20010919', '890'),
 ('20010920', '841'),
 ('20010921', '755'),
 ('20010925', '782'),
 ('20010926', '881'),
 ('20010927', '857'),
 ('20010928', '860'),
 ('20011001', '898'),
 ('20011002', '889'),
 ('20011003', '901'),
 ('20011004', '969'),
 ('20011005', '940'),
 ('20011009', '893'),
 ('20011010', '904'),
 ('20011011', '932'),
 ('20011012', '929'),
 ('20011015', '910'),
 ('20011016', '954'),
 ('20011017', '953'),
 ('20011018', '937'),
 ('20011019', '927'),
 ('20011022', '948'),
 ('20011023', '1000'),
 ('20011024', '974'),
 ('20011025', '966'),
 ('20011026', '979'),
 ('20011029', '985'),
 ('20011030', '982'),
 ('20011031', '970'),
 ('20011101', '955'),
 ('20011102', '976'),
 ('20011105', '998'),
 ('20011106', '1040'),
 ('20011107', '1020'),
 ('20011108', '1010'),
 ('20011109', '1003'),
 ('20011112', '997'),
 ('20011113', '993'),
 ('20011114', '995'),
 ('20011115', '1035'),
 ('20011116', '1041'),
 ('20011119', '1030'),
 ('20011120', '1005'),
 ('20011121', '1001'),
 ('20011122', '1008'),
 ('20011126', '1041'),
 ('20011127', '1044'),
 ('20011128', '1013'),
 ('20011129', '1000'),
 ('20011130', '1038'),
 ('20011203', '971'),
 ('20011204', '973'),
 ('20011205', '997'),
 ('20011206', '994'),
 ('20011207', '980'),
 ('20011210', '958'),
 ('20011211', '955'),
 ('20011212', '960'),
 ('20011213', '910'),
 ('20011214', '950'),
 ('20011217', '937'),
 ('20011218', '943'),
 ('20011219', '987'),
 ('20011220', '964'),
 ('20011221', '967'),
 ('20011225', '940'),
 ('20011226', '947'),
 ('20011227', '971'),
 ('20011228', '970'),
 ('20020104', '996'),
 ('20020107', '1009'),
 ('20020108', '977'),
 ('20020109', '985'),
 ('20020110', '991'),
 ('20020111', '980'),
 ('20020115', '951'),
 ('20020116', '965'),
 ('20020117', '960'),
 ('20020118', '953'),
 ('20020121', '965'),
 ('20020122', '956'),
 ('20020123', '974'),
 ('20020124', '966'),
 ('20020125', '951'),
 ('20020128', '972'),
 ('20020129', '965'),
 ('20020130', '962'),
 ('20020131', '967'),
 ('20020201', '960'),
 ('20020204', '961'),
 ('20020205', '942'),
 ('20020206', '926'),
 ('20020207', '913'),
 ('20020208', '911'),
 ('20020212', '896'),
 ('20020213', '889'),
 ('20020214', '886'),
 ('20020215', '875'),
 ('20020218', '855'),
 ('20020219', '801'),
 ('20020220', '811'),
 ('20020221', '859'),
 ('20020222', '847'),
 ('20020225', '862'),
 ('20020226', '831'),
 ('20020227', '864'),
 ('20020228', '860'),
 ('20020301', '874'),
 ('20020304', '948'),
 ('20020305', '956'),
 ('20020306', '965'),
 ('20020307', '978'),
 ('20020308', '1009'),
 ('20020311', '1045'),
 ('20020312', '1039'),
 ('20020313', '981'),
 ('20020314', '1003'),
 ('20020315', '996'),
 ('20020318', '990'),
 ('20020319', '1013'),
 ('20020320', '976'),
 ('20020322', '954'),
 ('20020325', '956'),
 ('20020326', '1000'),
 ('20020327', '987'),
 ('20020328', '965'),
 ('20020329', '912'),
 ('20020401', '915'),
 ('20020402', '919'),
 ('20020403', '944'),
 ('20020404', '912'),
 ('20020405', '886'),
 ('20020408', '908'),
 ('20020409', '877'),
 ('20020410', '882'),
 ('20020411', '900'),
 ('20020412', '870'),
 ('20020415', '896'),
 ('20020416', '917'),
 ('20020417', '942'),
 ('20020418', '944'),
 ('20020419', '967'),
 ('20020422', '982'),
 ('20020423', '995'),
 ('20020424', '996'),
 ('20020425', '993'),
 ('20020426', '971'),
 ('20020430', '967'),
 ('20020501', '992'),
 ('20020502', '994'),
 ('20020507', '1010'),
 ('20020508', '1038'),
 ('20020509', '1056'),
 ('20020510', '1066'),
 ('20020513', '1061'),
 ('20020514', '1076'),
 ('20020515', '1138'),
 ('20020516', '1114'),
 ('20020517', '1111'),
 ('20020520', '1176'),
 ('20020521', '1175'),
 ('20020522', '1180'),
 ('20020523', '1170'),
 ('20020524', '1156'),
 ('20020527', '1223'),
 ('20020528', '1269'),
 ('20020529', '1250'),
 ('20020530', '1233'),
 ('20020531', '1220'),
 ('20020603', '1209'),
 ('20020604', '1189'),
 ('20020605', '1205'),
 ('20020606', '1170'),
 ('20020607', '1208'),
 ('20020610', '1212'),
 ('20020611', '1218'),
 ('20020612', '1199'),
 ('20020613', '1190'),
 ('20020614', '1138'),
 ('20020617', '1108'),
 ('20020618', '1120'),
 ('20020619', '1160'),
 ('20020620', '1212'),
 ('20020621', '1139'),
 ('20020624', '1140'),
 ('20020625', '1179'),
 ('20020626', '1130'),
 ('20020627', '1140'),
 ('20020628', '1166'),
 ('20020701', '1155'),
 ('20020702', '1187'),
 ('20020703', '1222'),
 ('20020704', '1171'),
 ('20020705', '1223'),
 ('20020708', '1213'),
 ('20020709', '1270'),
 ('20020710', '1229'),
 ('20020711', '1171'),
 ('20020712', '1219'),
 ('20020715', '1170'),
 ('20020716', '1153'),
 ('20020717', '1171'),
 ('20020718', '1183'),
 ('20020719', '1177'),
 ('20020722', '1159'),
 ('20020723', '1185'),
 ('20020724', '1197'),
 ('20020725', '1181'),
 ('20020726', '1122'),
 ('20020729', '1116'),
 ('20020730', '1138'),
 ('20020731', '1104'),
 ('20020801', '1037'),
 ('20020802', '1041'),
 ('20020805', '1037'),
 ('20020806', '1031'),
 ('20020807', '1133'),
 ('20020808', '1105'),
 ('20020809', '1185'),
 ('20020812', '1132'),
 ('20020813', '1130'),
 ('20020814', '1168'),
 ('20020815', '1193'),
 ('20020816', '1177'),
 ('20020819', '1161'),
 ('20020820', '1187'),
 ('20020821', '1155'),
 ('20020822', '1194'),
 ('20020823', '1177'),
 ('20020826', '1219'),
 ('20020827', '1210'),
 ('20020828', '1189'),
 ('20020829', '1151'),
 ('20020830', '1138'),
 ('20020902', '1134'),
 ('20020903', '1072'),
 ('20020904', '1036'),
 ('20020905', '1070'),
 ('20020906', '1069'),
 ('20020909', '1073'),
 ('20020910', '1095'),
 ('20020911', '1139'),
 ('20020912', '1119'),
 ('20020913', '1056'),
 ('20020917', '1096'),
 ('20020918', '1067'),
 ('20020919', '1127'),
 ('20020920', '1155'),
 ('20020924', '1150'),
 ('20020925', '1140'),
 ('20020926', '1142'),
 ('20020927', '1178'),
 ('20020930', '1153'),
 ('20021001', '1090'),
 ('20021002', '1091'),
 ('20021003', '1083'),
 ('20021004', '1075'),
 ('20021007', '1038'),
 ('20021008', '1051'),
 ('20021009', '1046'),
 ('20021010', '1100'),
 ('20021011', '1095'),
 ('20021015', '1109'),
 ('20021016', '1139'),
 ('20021017', '1127'),
 ('20021018', '1110'),
 ('20021021', '1091'),
 ('20021022', '1074'),
 ('20021023', '1051'),
 ('20021024', '1036'),
 ('20021025', '1073'),
 ('20021028', '1049'),
 ('20021029', '1082'),
 ('20021030', '1091'),
 ('20021031', '1056'),
 ('20021101', '1094'),
 ('20021105', '1085'),
 ('20021106', '1084'),
 ('20021107', '1099'),
 ('20021108', '1066'),
 ('20021111', '1034'),
 ('20021112', '1052'),
 ('20021113', '1044'),
 ('20021114', '1030'),
 ('20021115', '1054'),
 ('20021118', '1093'),
 ('20021119', '1119'),
 ('20021120', '1143'),
 ('20021121', '1169'),
 ('20021122', '1144'),
 ('20021125', '1135'),
 ('20021126', '1130'),
 ('20021127', '1135'),
 ('20021128', '1170'),
 ('20021129', '1183'),
 ('20021202', '1172'),
 ('20021203', '1170'),
 ('20021204', '1149'),
 ('20021205', '1123'),
 ('20021206', '1123'),
 ('20021209', '1116'),
 ('20021210', '1125'),
 ('20021211', '1120'),
 ('20021212', '1152'),
 ('20021213', '1142'),
 ('20021216', '1137'),
 ('20021217', '1122'),
 ('20021218', '1095'),
 ('20021219', '1104'),
 ('20021220', '1089'),
 ('20021224', '1090'),
 ('20021225', '1098'),
 ('20021226', '1146'),
 ('20021227', '1141'),
 ('20021230', '1097'),
 ('20030106', '1095'),
 ('20030107', '1115'),
 ('20030108', '1121'),
 ('20030109', '1129'),
 ('20030110', '1108'),
 ('20030114', '1109'),
 ('20030115', '1122'),
 ('20030116', '1179'),
 ('20030117', '1186'),
 ('20030120', '1200'),
 ('20030121', '1216'),
 ('20030122', '1235'),
 ('20030123', '1234'),
 ('20030124', '1222'),
 ('20030127', '1225'),
 ('20030128', '1271'),
 ('20030129', '1272'),
 ('20030130', '1330'),
 ('20030131', '1308'),
 ('20030203', '1351'),
 ('20030204', '1320'),
 ('20030205', '1302'),
 ('20030206', '1299'),
 ('20030207', '1300'),
 ('20030210', '1300'),
 ('20030212', '1337'),
 ('20030213', '1309'),
 ('20030214', '1310'),
 ('20030217', '1321'),
 ('20030218', '1338'),
 ('20030219', '1375'),
 ('20030220', '1345'),
 ('20030221', '1327'),
 ('20030224', '1325'),
 ('20030225', '1307'),
 ('20030226', '1324'),
 ('20030227', '1308'),
 ('20030228', '1331'),
 ('20030303', '1399'),
 ('20030304', '1386'),
 ('20030305', '1374'),
 ('20030306', '1379'),
 ('20030307', '1345'),
 ('20030310', '1333'),
 ('20030311', '1290'),
 ('20030312', '1261'),
 ('20030313', '1260'),
 ('20030314', '1345'),
 ('20030317', '1314'),
 ('20030318', '1285'),
 ('20030319', '1300'),
 ('20030320', '1318'),
 ('20030324', '1318'),
 ('20030325', '1311'),
 ('20030326', '1332'),
 ('20030327', '1353'),
 ('20030328', '1377'),
 ('20030331', '1335'),
 ('20030401', '1350'),
 ('20030402', '1359'),
 ('20030403', '1390'),
 ('20030404', '1411'),
 ('20030407', '1445'),
 ('20030408', '1393'),
 ('20030409', '1394'),
 ('20030410', '1390'),
 ('20030411', '1372'),
 ('20030414', '1360'),
 ('20030415', '1361'),
 ('20030416', '1375'),
 ('20030417', '1369'),
 ('20030418', '1365'),
 ('20030421', '1377'),
 ('20030422', '1346'),
 ('20030423', '1336'),
 ('20030424', '1357'),
 ('20030425', '1347'),
 ('20030428', '1332'),
 ('20030430', '1349'),
 ('20030501', '1361'),
 ('20030502', '1370'),
 ('20030506', '1367'),
 ('20030507', '1388'),
 ('20030508', '1459'),
 ('20030509', '1430'),
 ('20030512', '1558'),
 ('20030513', '1557'),
 ('20030514', '1532'),
 ('20030515', '1540'),
 ('20030516', '1521'),
 ('20030519', '1537'),
 ('20030520', '1555'),
 ('20030521', '1531'),
 ('20030522', '1524'),
 ('20030523', '1529'),
 ('20030526', '1512'),
 ('20030527', '1527'),
 ('20030528', '1559'),
 ('20030529', '1584'),
 ('20030530', '1617'),
 ('20030602', '1626'),
 ('20030603', '1699'),
 ('20030604', '1627'),
 ('20030605', '1629'),
 ('20030606', '1686'),
 ('20030609', '1655'),
 ('20030610', '1659'),
 ('20030611', '1682'),
 ('20030612', '1706'),
 ('20030613', '1691'),
 ('20030616', '1645'),
 ('20030617', '1700'),
 ('20030618', '1685'),
 ('20030619', '1670'),
 ('20030620', '1667'),
 ('20030623', '1661'),
 ('20030624', '1640'),
 ('20030625', '1640'),
 ('20030626', '1631'),
 ('20030627', '1669'),
 ('20030630', '1646'),
 ('20030701', '1696'),
 ('20030702', '1681'),
 ('20030703', '1673'),
 ('20030704', '1630'),
 ('20030707', '1660'),
 ('20030708', '1708'),
 ('20030709', '1740'),
 ('20030710', '1784'),
 ('20030711', '1756'),
 ('20030714', '1776'),
 ('20030715', '1770'),
 ('20030716', '1731'),
 ('20030717', '1721'),
 ('20030718', '1691'),
 ('20030722', '1677'),
 ('20030723', '1700'),
 ('20030724', '1700'),
 ('20030725', '1712'),
 ('20030728', '1709'),
 ('20030729', '1699'),
 ('20030730', '1674'),

In [55]:
len(car)

41950

In [56]:
car[("NIKPRLRSP038060_07012003", '7951')]

0.020039986044121272

In [63]:
with open("car", 'w') as f:
    for key, v in car.items():
        articleid, code = key
        f.write('\t'.join([articleid, code, str(v)]))
        f.write('\n')

In [57]:
car[("NIKPRLRSP265673_04112010", "1833")]

0.0093587175676982381

In [58]:
matching["NIKPRLRSP265673_04112010"]

('20101104', ['1833'], ['奥村組'])

In [59]:
kabuka_data = load_kabuka("1833")
ed, em, ad, am = determine_interval(kabuka_data, market, pd.to_datetime("20101104"))
print(ed,em,ad,am)

[ 319.  315.  313.  309.  295.  285.  288.  296.  289.  298.  298.  297.
  300.  294.  294.  292.  295.  298.  295.  298.  305.  300.  310.  305.
  308.  308.  304.  301.  311.  304.  303.  307.  308.  306.  309.  315.
  316.  318.  317.  320.  312.  317.  317.  324.  331.  337.  344.  342.
  341.  342.  341.  338.  346.  350.  344.  341.  332.  330.  336.  329.
  329.  326.  336.  340.  329.  323.  317.  325.  328.  318.  320.  328.
  324.  314.  317.  324.  317.  321.  321.  323.  325.  323.  319.  325.
  332.  326.  324.  326.  324.  326.  330.  328.  327.  325.  325.  323.
  324.  326.  320.  326.  327.  325.  326.  327.  324.  328.  324.  322.
  324.  321.  324.  324.  321.  316.  317.  325.  322.  323.  329.  326.
  317.  320.  309.  296.  299.  298.  297.  297.  294.  298.  299.  296.
  296.  292.  294.  297.  312.  310.  315.  320.  319.  316.  323.  325.
  314.  312.  319.  326.  323.  327.  325.  328.  324.  326.  328.  328.
  325.  329.  325.  327.  327.  326.  320.  324.  323.  325.  319.  333.
  332.  337.  330.  337.  330.  323.  318.  315.  315.  320.  316.  316.
  327.  321.  309.  310.  317.  304.  308.  306.  303.  299.  294.  291.
  293.  291.  290.  293.  295.  287.  282.  279.  282.  279.  286.  291.
  278.  284.  292.  293.  298.  297.  289.  285.  284.  288.  283.  289.
  280.  286.] [ 894.67  880.54  881.27  874.96  874.01  870.67  872.44  872.29  867.7
  866.8   860.42  857.    850.06  837.71  838.71  829.22  833.29  829.56
  811.01  839.94  857.76  858.74  888.04  889.58  898.93  896.7   884.94
  873.9   888.57  885.08  884.63  898.29  896.28  893.59  891.48  903.06
  913.72  909.39  914.78  915.87  907.59  915.75  919.57  931.13  931.85
  941.29  954.13  944.02  959.01  966.4   957.55  949.76  944.72  956.03
  940.94  934.59  916.4   907.67  914.32  901.12  898.61  912.82  915.68
  911.09  891.78  883.01  881.57  883.5   892.16  883.47  885.17  904.63
  904.73  889.08  909.75  907.37  895.69  891.41  894.1   898.93  902.71
  905.65  897.64  910.81  927.31  924.38  922.44  930.38  936.38  938.91
  938.1   947.43  940.79  948.93  947.37  951.97  952.13  966.72  966.13
  979.58  978.81  985.26  989.39  995.68  990.79  995.54  985.99  989.42
  994.78  988.44  991.1   998.9   988.84  970.84  972.11  987.07  978.17
  978.2   996.71  997.63  977.64  987.04  956.72  931.74  944.64  932.1
  932.83  947.9   936.45  920.43  913.91  910.64  898.15  879.69  880.01
  859.82  859.    869.89  878.52  880.46  880.04  870.05  890.64  890.16
  859.21  858.33  850.37  856.79  866.44  878.56  878.83  892.38  887.48
  884.64  902.49  894.56  880.84  879.77  867.3   860.8   852.19  841.42
  828.39  830.98  836.89  847.24  841.51  861.02  861.21  857.7   854.39
  870.73  856.6   840.58  832.26  829.35  825.48  841.29  845.88  846.12
  865.51  861.27  849.5   850.69  859.18  845.93  857.09  861.17  857.62
  854.68  834.45  827.78  831.24  828.63  826.78  835.23  843.98  829.59
  824.79  817.73  807.31  811.79  819.62  829.21  804.67  811.4   819.42
  823.7   838.71  834.92  820.99  826.84  833.72  837.65  834.87  848.64
  844.71  852.09] [ 281.  281.  285.  294.] [ 803.3   803.12  816.33  834.98]

In [60]:
car[("NIKPRLRSP265675_04112010","8267")]

0.001599503984389683

In [61]:
matching["NIKPRLRSP265675_04112010"]

('20101104', ['8267', '9946'], ['イオン', 'ミニストップ'])

In [62]:
kabuka_data = load_kabuka("8267")
ed, em, ad, am = determine_interval(kabuka_data, market, pd.to_datetime("20101104"))
print(ed,em,ad,am)

[  820.   799.   803.   797.   777.   773.   775.   736.   740.   747.
   752.   745.   729.   706.   713.   703.   686.   692.   674.   696.
   714.   713.   733.   734.   735.   728.   750.   737.   747.   731.
   724.   717.   719.   714.   716.   725.   742.   739.   752.   761.
   752.   756.   757.   796.   796.   848.   880.   884.   886.   903.
   888.   881.   883.   896.   881.   913.   905.   912.   923.   902.
   903.   916.   942.   942.   921.   905.   892.   897.   916.   902.
   888.   908.   920.   899.   924.   924.   897.   888.   914.   916.
   907.   906.   898.   909.   932.   926.   926.   961.   975.   982.
   974.   994.   988.  1012.  1010.  1015.  1005.  1038.  1035.  1053.
  1061.  1090.  1104.  1105.  1092.  1060.  1060.  1072.  1090.  1072.
  1087.  1092.  1062.  1035.  1056.  1073.  1097.  1114.  1113.  1108.
  1071.  1081.  1042.  1022.  1043.  1033.  1031.  1043.  1017.  1001.
   987.   979.   969.   959.   940.   918.   923.   928.   943.   951.
   950.   936.   954.   960.   924.   927.   920.   917.   915.   927.
   939.   956.   964.   969.  1005.   991.   975.   981.   969.   963.
   964.   945.   930.   939.   945.   949.   933.   946.   943.   939.
   924.   930.   924.   912.   903.   905.   907.   916.   924.   929.
   950.   944.   925.   924.   924.   917.   932.   934.   938.   938.
   919.   912.   921.   919.   919.   928.   935.   926.   928.   908.
   904.   900.   916.   919.   897.   902.   907.   911.   910.   904.
   888.   894.   905.   911.   902.   919.   910.   919.] [ 894.67  880.54  881.27  874.96  874.01  870.67  872.44  872.29  867.7
  866.8   860.42  857.    850.06  837.71  838.71  829.22  833.29  829.56
  811.01  839.94  857.76  858.74  888.04  889.58  898.93  896.7   884.94
  873.9   888.57  885.08  884.63  898.29  896.28  893.59  891.48  903.06
  913.72  909.39  914.78  915.87  907.59  915.75  919.57  931.13  931.85
  941.29  954.13  944.02  959.01  966.4   957.55  949.76  944.72  956.03
  940.94  934.59  916.4   907.67  914.32  901.12  898.61  912.82  915.68
  911.09  891.78  883.01  881.57  883.5   892.16  883.47  885.17  904.63
  904.73  889.08  909.75  907.37  895.69  891.41  894.1   898.93  902.71
  905.65  897.64  910.81  927.31  924.38  922.44  930.38  936.38  938.91
  938.1   947.43  940.79  948.93  947.37  951.97  952.13  966.72  966.13
  979.58  978.81  985.26  989.39  995.68  990.79  995.54  985.99  989.42
  994.78  988.44  991.1   998.9   988.84  970.84  972.11  987.07  978.17
  978.2   996.71  997.63  977.64  987.04  956.72  931.74  944.64  932.1
  932.83  947.9   936.45  920.43  913.91  910.64  898.15  879.69  880.01
  859.82  859.    869.89  878.52  880.46  880.04  870.05  890.64  890.16
  859.21  858.33  850.37  856.79  866.44  878.56  878.83  892.38  887.48
  884.64  902.49  894.56  880.84  879.77  867.3   860.8   852.19  841.42
  828.39  830.98  836.89  847.24  841.51  861.02  861.21  857.7   854.39
  870.73  856.6   840.58  832.26  829.35  825.48  841.29  845.88  846.12
  865.51  861.27  849.5   850.69  859.18  845.93  857.09  861.17  857.62
  854.68  834.45  827.78  831.24  828.63  826.78  835.23  843.98  829.59
  824.79  817.73  807.31  811.79  819.62  829.21  804.67  811.4   819.42
  823.7   838.71  834.92  820.99  826.84  833.72  837.65  834.87  848.64
  844.71  852.09] [ 944.  955.  964.  985.] [ 803.3   803.12  816.33  834.98]